excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ReasonOnFaith.github.io
title: REASON ON FAITH<br/>the microblog
tagline: commenting on faith and religion through the eyes of reason
description: This site is where I post content too long for Twitter and too off the cuff for my formal blog, ReasonOnFaith.org.<br /><br />You probably arrived here from a Twitter.com conversation, where I wanted to say more than 140 characters to get some nuance across.
paginate: 5
